# Generated by Django 5.2.5 on 2025-09-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Mukofot nomi')),
                ('experience', models.CharField(max_length=150, verbose_name='Tajribangiz')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_language', models.CharField(max_length=100, verbose_name='Dasturlash tili')),
                ('experience', models.CharField(max_length=150, verbose_name='Tajribangiz')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ism')),
                ('about', models.TextField(blank=True, null=True, verbose_name="O'zingiz haqingizda")),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Rasmi')),
            ],
            options={
                'verbose_name': 'Portfolio',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Skillar')),
            ],
        ),
    ]
