# Generated by Django 5.2.5 on 2025-09-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='experience',
            field=models.CharField(max_length=150, verbose_name='Tajribangiz: '),
        ),
        migrations.AlterField(
            model_name='awards',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Mukofot nomi: '),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name="O'zingiz haqingizda: "),
        ),
    ]
